### ISSUE TITLE
get_text in documentation should be read_text

### ISSUE THREAD

**Issue by tobi-lipede-oodle** [yukihiko-shinoda/pytest-resource-path#9]
Hello - thanks for this package!

I just noticed that a couple of examples in the documentation are like:

```python
def test_method(resource_path):
    text_test_resource = (resource_path / 'test_resource.txt').get_text()
```

but they should instead be:

```python
def test_method(resource_path):
    text_test_resource = (resource_path / 'test_resource.txt').read_text()
```

**Comment by yukihiko-shinoda** [comment]
I'm sorry for find late, and thank you very much for your feedback!
If this Issue wasn't posted, I didn't notice mistakes in the documentation,
so it was much helpful.

**Comment by TLipede** [comment]
Thank you! :)
